name: wradlib
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - black
  - bottleneck
  - cartopy
  - coverage
  - codecov
  - dask
  - deprecation
  - gdal
  - git
  - flake8
  - h5py
  - h5netcdf
  - ipyparallel
  - isort
  - jupyter
  - matplotlib
  - nbconvert
  - nbformat
  - nbsphinx
  - netCDF4
  - notebook
  - numpy
  - pandoc
  - pint
  - pint-xarray
  - pip
  - psutil
  - pytest
  - pytest-cov
  - pytest-sugar
  - pytest-xdist
  - requests
  - scipy
  - semver
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx_rtd_theme
  - tqdm
  - wetterdienst
  - xarray
  - xmltodict
